apiVersion: apps/v1
kind: Deployment
metadata:
  name: scriptrunner-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: scriptrunner-operator
  template:
    metadata:
      labels:
        name: scriptrunner-operator
    spec:
      serviceAccountName: scriptrunner-operator
      containers:
        - name: scriptrunner-operator
          # Replace this with the built image name
          image: scriptrunner:latest
          command:
          - scriptrunner-operator
          imagePullPolicy: Never
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "scriptrunner-operator"
